# Generated by Django 3.2.9 on 2021-12-14 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0003_chiacustomers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chiaCustomers',
            new_name='chiaCustomer',
        ),
    ]
